-- MySQL Script generated by MySQL Workbench
-- 08/24/18 21:38:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd-tareas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd-tareas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-tareas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `bd-tareas` ;

-- -----------------------------------------------------
-- Table `bd-tareas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-tareas`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellido_usuario` VARCHAR(45) NOT NULL,
  `rut_usuario` VARCHAR(13) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `rol_usuario` TINYINT(1) NOT NULL,
  `estado_usuario` TINYINT(1) NOT NULL,
  `correo_usuario` VARCHAR(45) NULL,
  `password_usuario` VARCHAR(32) NULL,
  `avatar_usuario` VARCHAR(80) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bd-tareas`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-tareas`.`tareas` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `titulo_tarea` VARCHAR(45) NOT NULL,
  `descripcion_tarea` TEXT(2000) NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `estado_tarea` TINYINT(1) NULL,
  `publicado_por` VARCHAR(45) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_tareas_usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tareas_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd-tareas`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
